local map = vim.api.nvim_set_keymap

map('n', '<space>e', ':NvimTreeToggle<CR>', { noremap=true })
map('n', '<space>r', ':NvimTreeRefresh<CR>', { noremap=true })
map('n', 'ff',       ':Telescope find_files<CR>', { noremap=true, silent=true })
map('n', 'gg',       ':LazyGit<CR>', { noremap=true, silent=true })
map('n', 'fb',       ':Telescope buffers<CR>', { noremap=true, silent=true })
map('n', '<C-o>',    ':BufferLineMovePrev<CR>', { noremap=true })
map('n', '<C-p>',    ':BufferLineMoveNext<CR>', { noremap=true })
map('n', '<space>q', ':bdelete!<CR>', { noremap=true })
map('n', 'gd',       ':lua vim.lsp.buf.definition()<CR>', { noremap=true, silent=true })
map('n', 'gc',       ':lua vim.lsp.buf.declaration()<CR>', { noremap=true, silent=true })
map('n', 'gr',       ':lua vim.lsp.buf.references()<CR>', { noremap=true, silent=true })
map('n', 'gi',       ':lua vim.lsp.buf.implementation()<CR>', { noremap=true, silent=true })
map('n', 'K',        ':lua vim.lsp.buf.hover()<CR>', { noremap=true, silent=true })
map('n', '<C-l>',    ':noh<CR>', { noremap=true })
map('n', 'uu',       ':undo<CR>', { noremap=true, silent=true })
map('n', 'rr',       ':redo<CR>', { noremap=true, silent=true })
map("n", "gr", "<cmd>Lspsaga rename<cr>", {silent = true, noremap = true})
map("n", "gx", "<cmd>Lspsaga code_action<cr>", {silent = true, noremap = true})
map("x", "gx", ":<c-u>Lspsaga range_code_action<cr>", {silent = true, noremap = true})
map("n", "K",  "<cmd>Lspsaga hover_doc<cr>", {silent = true, noremap = true})
map("n", "go", "<cmd>Lspsaga show_line_diagnostics<cr>", {silent = true, noremap = true})
map("n", "gj", "<cmd>Lspsaga diagnostic_jump_next<cr>", {silent = true, noremap = true})
map("n", "gk", "<cmd>Lspsaga diagnostic_jump_prev<cr>", {silent = true, noremap = true})
map("n", "<C-u>", "<cmd>lua require('lspsaga.action').smart_scroll_with_saga(-1, '<c-u>')<cr>", {})
map("n", "<C-d>", "<cmd>lua require('lspsaga.action').smart_scroll_with_saga(1, '<c-d>')<cr>", {})

