vim.api.nvim_set_keymap('n', '<space>e', ':NvimTreeToggle<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<space>r', ':NvimTreeRefresh<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<space>t', ':TroubleToggle<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<C-q>', ':qa!<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', 'ff', ':Telescope find_files<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', '<F1>', ':FloatermToggle!<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'rr', ':RnvimrToggle<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'gg', ':LazyGit<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'fg', ':Telescope live_grep<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'fb', ':Telescope buffers<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'fh', ':Telescope help_tags<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', '<C-i>', ':BufferLineCycleNext<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<C-u>', ':BufferLineCyclePrev<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<space>q', ':bdelete!<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', 'gd', ':lua vim.lsp.buf.definition()<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'gc', ':lua vim.lsp.buf.declaration()<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'gr', ':lua vim.lsp.buf.references()<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'gi', ':lua vim.lsp.buf.implementation()<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', 'K', ':lua vim.lsp.buf.hover()<CR>', { noremap=true, silent=true })
vim.api.nvim_set_keymap('n', '<C-l>', ':noh<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<C-z>', ':undo<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', '<C-y>', ':redo<CR>', { noremap=true })
vim.api.nvim_set_keymap('n', 'ca', ':CodeActionMenu<CR>', { noremap=true, silent=true })


