local Plug = vim.fn['plug#']

vim.call('plug#begin', '~/.config/nvim/plugged')
Plug('vim-scripts/delimitMate.vim')
Plug('nvim-lua/plenary.nvim')
Plug('nvim-telescope/telescope.nvim')
Plug('airblade/vim-rooter')
Plug('kyazdani42/nvim-web-devicons')
Plug('kyazdani42/nvim-tree.lua')
Plug('neovim/nvim-lspconfig')
Plug('goolord/alpha-nvim')
Plug('williamboman/nvim-lsp-installer')
Plug('hrsh7th/cmp-nvim-lsp')
Plug('hrsh7th/cmp-vsnip')
Plug('hrsh7th/cmp-buffer')
Plug('hrsh7th/cmp-path')
Plug('hrsh7th/cmp-cmdline')
Plug('hrsh7th/vim-vsnip')
Plug('hrsh7th/nvim-cmp')
Plug('folke/tokyonight.nvim', { branch='main' })
Plug('nvim-treesitter/nvim-treesitter', {['do']='TSUpdate'})
Plug('akinsho/bufferline.nvim')
Plug('tami5/lspsaga.nvim')
Plug('voldikss/vim-floaterm')
Plug('folke/which-key.nvim')
Plug('folke/trouble.nvim')
Plug('vimwiki/vimwiki')
vim.call('plug#end')

require('plugins.alpha')
require('plugins.lsp')
require('plugins.cmp')
require('plugins.nvim-tree')
require('plugins.nvim-treesitter')
require('plugins.bufferline')
require('plugins.lspsaga')
require('plugins.floaterm')
require('plugins.which-key')
require('plugins.trouble')
